import dotenv
import os

dotenv.load_dotenv()

# Load environment variable from .env file

# KAFKA INFORMATION
KAFKA_BROKER_URL = os.getenv("KAFKA_BROKER")
STOCK_QUOTES_TOPIC = os.getenv("STOCK_QUOTES_TOPIC")
STOCK_CANDLES_TOPIC = os.getenv("STOCK_CANDLES_TOPIC")
STOCK_COMPANY_PROFILE_TOPIC = os.getenv("STOCK_COMPANY_PROFILE_TOPIC")
STOCK_NEWS_TOPIC = os.getenv("STOCK_NEWS_TOPIC")
STOCK_FINENCIAL_TOPIC = os.getenv("STOCK_FINENCIAL_TOPIC")
STOCK_EARNINGS_TOPIC = os.getenv("STOCK_EARNINGS_TOPIC")
STOCK_MARKET_STETUS_TOPIC = os.getenv("STOCK_MARKET_STETUS_TOPIC")

# MINIO INFORMATION
MINIO_ROOT_USER = os.getenv("MINIO_ROOT_USER")
MINIO_ROOT_PASSWORD = os.getenv("MINIO_ROOT_PASSWORD")
MINIO_ENDPOINT = os.getenv("MINIO_ENDPOINT")
RAW_DATA_BUCKET = os.getenv("RAW_DATA_BUCKET")
PROCESSED_DATA_BUCKET = os.getenv("PROCESSED_DATA_BUCKET")
GOLD_DATA_BUCKET = os.getenv("GOLD_DATA_BUCKET")


# AIRFLOW INFORMATION

AIRFLOW_UIO = os.getenv("AIRFLOW_UIO")

# DATABASE INFORMATION

DATABASE_USER = os.getenv("POSTGRES_USER")
DATABASE_PASSWORD = os.getenv("POSTGRES_PASSWORD")
DATABASE_DB = os.getenv("POSTGRES_DB")
