import dotenv
import os

dotenv.load_dotenv()

# Load environment variable from .env file

# KAFKA INFORMATION
KAFKA_BROKER_URL = os.getenv("KAFKA_BROKER")
KAFKA_TOPIC = os.getenv("KAFKA_TOPIC")

# MINIO INFORMATION
MINIO_ROOT_USER = os.getenv("MINIO_ROOT_USER")
MINIO_ROOT_PASSWORD = os.getenv("MINIO_ROOT_PASSWORD")
MINIO_ENDPOINT = os.getenv("MINIO_ENDPOINT")
RAW_DATA_BUCKET = os.getenv("RAW_DATA_BUCKET")
PROCESSED_DATA_BUCKET = os.getenv("PROCESSED_DATA_BUCKET")
GOLD_DATA_BUCKET = os.getenv("GOLD_DATA_BUCKET")


# AIRFLOW INFORMATION

AIRFLOW_UIO = os.getenv("AIRFLOW_UIO")

# DATABASE INFORMATION

DATABASE_USER = os.getenv("POSTGRES_USER")
DATABASE_PASSWORD = os.getenv("POSTGRES_PASSWORD")
DATABASE_DB = os.getenv("POSTGRES_DB")
