import os
from dotenv import load_dotenv

load_dotenv()

# STOCK MARKET API INFORMATION

STOCK_API_KEY = os.getenv("STOCK_API_KEY")
STOCK_API_URL = os.getenv("STOCK_API_URL")
STOCK_SYMBOLS = os.getenv("STOCK_SYMBOLS").split(",")

# STOCK MARKET ENDPOINT

STOCK_QUOTES = os.getenv("STOCK_QUOTES")
STOCK_CANDLES = os.getenv("STOCK_CANDLES")
STOCK_COMPANY_PROFILE = os.getenv("STOCK_COMPANY_PROFILE")
STOCK_NEWS = os.getenv("STOCK_NEWS")
STOCK_FINENCIAL = os.getenv("STOCK_FINENCIALS")
STOCK_EARNINGS = os.getenv("STOCK_EARNINGS")
STOCK_MARKET_STETUS = os.getenv("STOCK_MARKET_STATUS")
